### ISSUE TITLE
Feature request: Display style in selection

### ISSUE THREAD

**Issue by chrfickinger** [rasteiner/k3-awesome-picker#11]
see screenshot
![screenshot](https://user-images.githubusercontent.com/91317/96444096-f3421080-120d-11eb-8d7b-ea747f4923ea.jpg)

**Comment by chrfickinger** [comment]
... and if you want it even more user friendly, show the real name `Birthday Cake (duotone)` instead of the class name `fad fa-birthday-cake` in panel field :-)

**Comment by rasteiner** [comment]
style is now displayed in the picker. :)

> and if you want it even more user friendly, show the real name Birthday Cake (duotone) instead of the class name fad fa-birthday-cake in panel field :-)

This kinda conflicts with the free text input idea, doesn't it?

**Comment by chrfickinger** [comment]
> This kinda conflicts with the free text input idea, doesn't it?

yes it does. forget about the idea.

**Comment by chrfickinger** [comment]
... but the style description looks great.
