### ISSUE TITLE
Layout broken in Kirby 4

### ISSUE THREAD

**Issue by Werbschaft** [rasteiner/k3-awesome-picker#18]
While the Picker still works as it's named (awesome!) the Layout seems a bit out of date and a bit buggy. Maybe any way to fix styling issues?

<img width="783" alt="Bildschirmfoto 2024-01-23 um 15 43 54" src="https://github.com/rasteiner/k3-awesome-picker/assets/2178466/d331288e-9210-40dd-a04b-1f834b947df5">

**Comment by rasteiner** [comment]
There was a kirby 4 branch. I've now merged that into main and created a new tagged release. 
You should be able to update either with composer: `composer require rasteiner/k3-awesome-picker:0.3.0 -W` or simply by [downloading the release zip](https://github.com/rasteiner/k3-awesome-picker/archive/refs/tags/0.3.0.zip)

**Comment by Werbschaft** [comment]
Amazing!! Thanks so much!
