### ISSUE TITLE
Possibility of free input

### ISSUE THREAD

**Issue by Werbschaft** [rasteiner/k3-awesome-picker#5]
In some cases it would be very helpful if you could freely enter the text or the icon! Maybe it would make sense that it is not a select field but a text field?

**Comment by rasteiner** [comment]
What is the use case for this? 

The whole point, for me, of this plugin is that not skilled editor people can be sure that when an icon is selected, that icon will work. This is why it's a "picker": it lets you search and choose an icon. It doesn't, and imho shouldn't, let you *declare the wish for an icon*. Don't know if this makes sense to you.

**Comment by Werbschaft** [comment]
I can of course absolutely understand that! We mostly use Font Awesome. However, if we simply cannot find an icon, we create a second icon file ourselves with the few icons that we add manually. It is then no longer possible to enter this in the same field.

**Comment by chrfickinger** [comment]
For custom sets it would be a great benefit. An autocomplete by typing would complete the feature. So you could decide to pick or to type an icon.

**Comment by rasteiner** [comment]
okay, what if the meta data config would accept an array of paths? Or maybe even directly the metadata?
This could allow you to insert custom metadata and your custom set would then show up in the picker.

**Comment by Werbschaft** [comment]
Sometimes we misuse the field to enter other values. For example, to enter a simple 1. instead of an icon, hence the free entry

**Comment by chrfickinger** [comment]
You could use a text field to type your value manualy and an additional picker (click on search lens) which fills/replaces the text field with the icon code you've picked. This would be the most flexible way. The best of both worlds :-)

**Comment by Werbschaft** [comment]
That would be amazing! This would have also a nice side effect. If I load all icons with all styles, that Backend get really slow, so I could easily load only one style and change for example fas to fal manually

**Comment by chrfickinger** [comment]
The speed is not a problem in my opinion because it's panel only and not website. If you want to choose from 10000 icons, of course they all have to be loaded to display.
But the usage of a text field would probably allow to remove an icon once selected (issue :https://github.com/rasteiner/k3-awesome-picker/issues/3)

**Comment by rasteiner** [comment]
> But the usage of a text field would probably allow to remove an icon once selected (issue :#3)

you can remove an icon by clicking the ![image](https://user-images.githubusercontent.com/6684137/96442180-fd164480-120a-11eb-9d40-2bd23feb244d.png) button

But yes, changing the icon without opening the dropdown seems handy

**Comment by chrfickinger** [comment]
Of course a solution with an minus icon is working as well. Haven't thought about this idea.
Another idea would be showing a blank icon in the first row to "reset" the selection. 

I don't know what's better, both works for.

**Comment by Werbschaft** [comment]
I also have tested a bit and that there's no free input or editing the icons name is really a little problem for us. I also haven't the option to open console and change the value manually or another simple hack ...

No simple way to change the filed type to a text field and trigger the Dropdown from a simple Caret or similar? A text field would make some of the things maybe easier

**Comment by chrfickinger** [comment]
After installing the latest files I see the minus symbol now and it is working like described above. But to be honest, it is a little confused, you don't get it directly how it is working. It took me a time to click the lens. The behavior before was more intiutive.

Maybe this would be the perfect behavior:
Couldn't be the text field the search field itself and start typing would show the icon list directly. So you would be able to pick an icon or you could just type your own.
The search icon (and the x icon if opened) can then be removed as well and only a minus-icon is necessary.

Sorry for the extra work, this idea just came up now.

**Comment by rasteiner** [comment]
The problem with that, at least for me, is that when I want to change an icon, maybe I don't know if there is a better one. If I need to delete the current value to search for a new one, there's no easy way to get back to the original value (I'd have to either remember what was there, or click the kirby revert button which might also revert other stuff, or ctrl-z that doesn't exist on mobile). 

Therefore I'd prefer to keep search and value separated. 

Maybe there's a better way to make the "open dropdown" more evident, maybe revert back to the "[angle down icon](https://getkirby.com/docs/reference/panel/icons/angle-down)"

**Comment by Werbschaft** [comment]
Totally agree! A simple search icon would also do a good job

**Comment by chrfickinger** [comment]
> If I need to delete the current value to search for a new one, there's no easy way to get back to the original value

That's right. Once changed, the old one is gone. But 2 input fields if expanded (one to type and one to search) are really confusing. Isn't there another way to get back to the lastest saved icon?

**Comment by chrfickinger** [comment]
I don't like these layout

![sc02](https://user-images.githubusercontent.com/91317/96450296-4c15a700-1216-11eb-854c-95bf54ede797.jpg)

**Comment by chrfickinger** [comment]
> Maybe there's a better way to make the "open dropdown" more evident, maybe revert back to the "angle down icon"

Yes, I definitly prefer the angle symbol as well if you want to keep that behavior. Maybe the minus symbol looks better left beside the text if right site is used for search actions.

... and also ESC key should close the list.

**Comment by rasteiner** [comment]
It now looks like this:

![image](https://user-images.githubusercontent.com/6684137/96458475-41144400-1221-11eb-988e-565a4e9d43db.png)
I think this is a compromise I'm happy about, for now. :)

**Comment by chrfickinger** [comment]
Looks great Roman, good work!

**Comment by Werbschaft** [comment]
Looks very good! But for a free input there seems to be no way?

**Comment by chrfickinger** [comment]
It is possible now. Just type!

**Comment by Werbschaft** [comment]
OMG!!!! That's so amazing! Roman you need a "buy me a beer" Link or something!

Small hint: if you change the search field to type="search" most browser will display a times icon to clear search, check screenshot

<img width="319" alt="Bildschirmfoto 2020-10-19 um 15 54 16" src="https://user-images.githubusercontent.com/2178466/96460485-8a659300-1223-11eb-8094-2ce7b9912dfe.png">

**Comment by rasteiner** [comment]
@Werbschaft 
you're right. I had used the kirby component for text boxes, because that came with the styles, but it didn't allow me to set the input type to "search". So it's now a plain old html input.

PS: nice design with the text ellipsis. I'll steal that :)
Oops, already stolen - it's in the latest release 

PPS: i have a "buymeacoffee" page, but I don't promote it any longer because I have like 13 coffees there and I'm unable to withdraw them. :/

**Comment by Werbschaft** [comment]
Ahh ok, it's absolut no problem and the plugin is really amazing!! I have found the coffee link and send you a few. Have seen I send you a while ago also some for your great translation plugin 😄
