### ISSUE TITLE
Optical and usibility problems

### ISSUE THREAD

**Issue by Werbschaft** [rasteiner/k3-awesome-picker#6]
The field does not quite match the other standard fields. The following consideration could possibly be in the room:

• Use a normal text field with a magnifying glass. Before: and after: could also be used here. With before: the icon is displayed if one is selected with after: could be a magnifying glass
• the field is significantly higher than the standard fields, the whole layout is messed up when working with columns
• the dropdown should be positioned absolutely, otherwise the layout will also be totally confused when opening. A modal window would be better anyway

**Comment by rasteiner** [comment]
in the latest version the field has now the same height as the text field, and when open it takes up the same space as 4 text fields. 
It should therefore now maintain the kirby vertical rhythm.

I personally don't like it when stuff covers other stuff, so I'd prefer to avoid modals and go with the "structure field" approach. 
You can however position it absolutely by providing your [own panel stylesheet](https://getkirby.com/docs/reference/system/options/panel#custom-panel-css).

something like
```css 
.afp-dropdown {
    position: absolute;
}
```
should work (after the latest version)

**Comment by chrfickinger** [comment]
I don't like it as well when stuff covers other stuff. But if height is not limited the page is very long with 10000 icons.
Maybe it would be helpfull to set `max-height` of `"afp-list-container"` to `250px` which creates a vertical scrollbar.

**Comment by Werbschaft** [comment]
I have seen that it has now the same height, much better 😃 the rest can be done really easy with custom css

**Comment by rasteiner** [comment]
> Maybe it would be helpfull to set `max-height` of `"afp-list-container"` to `250px` which creates a vertical scrollbar.

that should already be the case, isn't it for you? If it's not, what browser are you using?

**Comment by chrfickinger** [comment]
> that should already be the case, isn't it for you? If it's not, what browser are you using?
Yes, indeed. After clearing the cache it is working.

**Comment by Werbschaft** [comment]
All seems to be fine!
