### ISSUE TITLE
Error in Config option "sprites‑folder"

### ISSUE THREAD

**Issue by chrfickinger** [rasteiner/k3-awesome-picker#9]
`sprites‑folder: true` aborts rendering of panel

**Comment by rasteiner** [comment]
uhm, `sprites‑folder: true` is not a valid value. It expects a path to the folder containing the sprites :/

You think this needs any fixing?

**Comment by chrfickinger** [comment]
uh .. got it. Nope no fix necessary.
My mistake. I used this option in the blueprint :-)
